import {z} from "zod";

export const BlockParagraphSchema = z.object({
  type: z.literal("paragraph"),
  text: z.string().min(1),
  _id: z.string().optional(),
});

export const BlockHeadingSchema = z.object({
  type: z.literal("heading"),
  text: z.string().min(1),
  _id: z.string().optional(),
});

export const BlockQuoteSchema = z.object({
  type: z.literal("quote"),
  text: z.string().min(1),
  cite: z.string().optional(),
  _id: z.string().optional(),
});

export const BlockImageSchema = z.object({
  type: z.literal("image"),
  url: z.string().min(1),
  caption: z.string().optional(),
  _id: z.string().optional(),
});

export const BlockVideoSchema = z.object({
  type: z.literal("video"),
  url: z.string().min(1),
  caption: z.string().optional(),
  _id: z.string().optional(),
});

export const BlockCodeSchema = z.object({
  type: z.literal("code"),
  text: z.string().min(1),
  language: z.string().optional(),
  title: z.string().optional(),
  _id: z.string().optional(),
});

export const BlockSchema = z.discriminatedUnion("type", [
  BlockParagraphSchema,
  BlockHeadingSchema,
  BlockQuoteSchema,
  BlockImageSchema,
  BlockVideoSchema,
  BlockCodeSchema,
]);

export const GeneratedArticleSchema = z.object({
  title: z.string().min(1),
  subtitle: z.string().default(""),
  excerpt: z.string().min(1),
  coverImage: z.string().default("https://pub-c1d80f0f7327493997a3c1285f43a9ea.r2.dev/amrit_logo.png"),
  videoUrl: z.string().default(""),
  author: z
    .object({
      name: z.string().default("Neural Author"),
      role: z.string().default("Systems Research Agent"),
      avatar: z.string().default("https://pub-c1d80f0f7327493997a3c1285f43a9ea.r2.dev/amrit_logo.png"),
    })
    .default({
      name: "Neural Author",
      role: "Systems Research Agent",
      avatar: "https://pub-c1d80f0f7327493997a3c1285f43a9ea.r2.dev/amrit_logo.png",
    }),
  tags: z.array(z.string()).default([]),
  accent: z.string().default("#6366f1"),
  featured: z.boolean().default(false),
  blocks: z.array(BlockSchema).min(1),
  slug: z.string().optional(),
  published: z.boolean().default(false),
  private: z.boolean().default(true),
  aiGenerated: z.literal(true).default(true),
});

/**
 * Normalizes and guarantees valid block IDs and fallback defaults for an ArticleDraft.
 *
 * @param {any} raw
 * @param {import("./types").GenerateArticleRequest} [request]
 * @returns {any}
 */
export function sanitizeArticleDraft(raw, request = {}) {
  let normalizedRaw = raw;
  if (Array.isArray(raw)) {
    if (raw.length > 0 && typeof raw[0] === "object" && raw[0] !== null && ("blocks" in raw[0] || "title" in raw[0])) {
      normalizedRaw = raw[0];
    } else {
      normalizedRaw = {
        title: request.topic || "Systems Research Brief",
        subtitle: request.angle || "",
        excerpt: "Systems research notes generated by containerized agent.",
        blocks: raw,
      };
    }
  }

  const parsed = GeneratedArticleSchema.safeParse(normalizedRaw);
  const data = parsed.success ? parsed.data : normalizedRaw;

  const blocks = Array.isArray(data?.blocks) ? data.blocks : [];
  const normalizedBlocks = blocks.map((b) => {
    const type = ["paragraph", "heading", "quote", "image", "video", "code"].includes(b.type)
      ? b.type
      : "paragraph";
    const _id = b._id || crypto.randomUUID();

    if (type === "paragraph" || type === "heading") {
      return {type, text: String(b.text || "").trim() || "...", _id};
    }
    if (type === "quote") {
      return {type, text: String(b.text || "").trim() || "...", cite: b.cite ? String(b.cite).trim() : undefined, _id};
    }
    if (type === "code") {
      return {
        type,
        text: String(b.text || "").trim() || "...",
        language: b.language ? String(b.language).trim() : undefined,
        title: b.title ? String(b.title).trim() : undefined,
        _id,
      };
    }
    if (type === "image") {
      return {
        type,
        url: String(b.url || "https://pub-c1d80f0f7327493997a3c1285f43a9ea.r2.dev/amrit_logo.png"),
        caption: b.caption ? String(b.caption).trim() : undefined,
        _id,
      };
    }
    if (type === "video") {
      return {
        type,
        url: String(b.url || ""),
        caption: b.caption ? String(b.caption).trim() : undefined,
        _id,
      };
    }
    return {type: "paragraph", text: String(b.text || "").trim() || "...", _id};
  });

  if (normalizedBlocks.length === 0) {
    normalizedBlocks.push({
      type: "paragraph",
      text: "Synthesis generated by Upstash Box Custom Agent.",
      _id: crypto.randomUUID(),
    });
  }

  const tags = Array.isArray(data?.tags) && data.tags.length > 0
    ? data.tags.map((t) => String(t).trim()).filter(Boolean)
    : ["Research", "Neural Systems", "Upstash Box"];

  return {
    title: String(data?.title || request.topic || "Untitled Research Brief").trim(),
    subtitle: String(data?.subtitle || request.angle || "").trim(),
    excerpt: String(data?.excerpt || (normalizedBlocks[0]?.text || "").slice(0, 200)).trim(),
    coverImage: String(
      data?.coverImage ||
        "https://pub-c1d80f0f7327493997a3c1285f43a9ea.r2.dev/amrit_logo.png"
    ).trim(),
    videoUrl: String(data?.videoUrl || "").trim(),
    author: {
      name: String(data?.author?.name || "Neural Author").trim(),
      role: String(data?.author?.role || "Systems Research Agent").trim(),
      avatar: String(data?.author?.avatar || "https://pub-c1d80f0f7327493997a3c1285f43a9ea.r2.dev/amrit_logo.png").trim(),
    },
    tags,
    accent: String(data?.accent || request.accent || "#6366f1").trim(),
    featured: Boolean(data?.featured),
    blocks: normalizedBlocks,
    slug: data?.slug ? String(data.slug).trim() : undefined,
    published: false,
    private: true,
    aiGenerated: true,
    isFallback: Boolean(raw?.isFallback),
    fallbackNotice: raw?.fallbackNotice || undefined,
  };
}
